# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface2.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(998, 661)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.searchLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.searchLineEdit.setGeometry(QtCore.QRect(80, 10, 811, 31))
        self.searchLineEdit.setStyleSheet("QLineEdit {\n"
"    border: 3px solid rgb(112, 111, 142);\n"
"    border-radius: 15px;\n"
"    color: rgb(105, 129, 141);\n"
"    padding-left: 8px;\n"
"}")
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.imageLabel = QtWidgets.QLabel(self.centralwidget)
        self.imageLabel.setGeometry(QtCore.QRect(70, 120, 601, 471))
        self.imageLabel.setStyleSheet("border-radius: 20px;\n"
"")
        self.imageLabel.setText("")
        self.imageLabel.setObjectName("imageLabel")
        self.aboutLabel = QtWidgets.QLabel(self.centralwidget)
        self.aboutLabel.setGeometry(QtCore.QRect(680, 80, 301, 511))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.aboutLabel.setFont(font)
        self.aboutLabel.setStyleSheet("color-radius: 5px;\n"
"border-radius: 20px")
        self.aboutLabel.setText("")
        self.aboutLabel.setObjectName("aboutLabel")
        self.leftButton = QtWidgets.QPushButton(self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(400, 600, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.leftButton.setFont(font)
        self.leftButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius:15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"    image: url(:/icons/left_icon.png);\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }")
        self.leftButton.setText("")
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(self.centralwidget)
        self.rightButton.setGeometry(QtCore.QRect(540, 600, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.rightButton.setFont(font)
        self.rightButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"    image: url(:/icons/right_icon.png);\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }")
        self.rightButton.setText("")
        self.rightButton.setObjectName("rightButton")
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(900, 10, 81, 31))
        self.searchButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius: 0px;\n"
"    border-bottom-right-radius: 0px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }")
        self.searchButton.setObjectName("searchButton")
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(470, 600, 61, 51))
        self.saveButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: #5c55e9;\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 10px;\n"
"    border-top-left-radius: 10px;\n"
"    border-bottom-right-radius: 10px;\n"
"    border-bottom-left-radius:10px;\n"
"    color-radius: 10px;\n"
"    padding: 10px;\n"
"\n"
"    \n"
"    image: url(:/icons/star.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
"    \n"
" }")
        self.saveButton.setText("")
        self.saveButton.setObjectName("saveButton")
        self.stylelineLabel = QtWidgets.QLabel(self.centralwidget)
        self.stylelineLabel.setGeometry(QtCore.QRect(0, -10, 51, 671))
        self.stylelineLabel.setStyleSheet("background-color:rgb(154, 151, 233)")
        self.stylelineLabel.setText("")
        self.stylelineLabel.setObjectName("stylelineLabel")
        self.headertextLabel = QtWidgets.QLabel(self.centralwidget)
        self.headertextLabel.setGeometry(QtCore.QRect(80, 80, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.headertextLabel.setFont(font)
        self.headertextLabel.setText("")
        self.headertextLabel.setObjectName("headertextLabel")
        self.infoButton = QtWidgets.QPushButton(self.centralwidget)
        self.infoButton.setGeometry(QtCore.QRect(10, 620, 31, 31))
        self.infoButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(61, 61, 61);\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius:15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"    image: url(:/icons/info.png);\n"
"\n"
"}\n"
"QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }")
        self.infoButton.setText("")
        self.infoButton.setObjectName("infoButton")
        self.savedButton = QtWidgets.QPushButton(self.centralwidget)
        self.savedButton.setGeometry(QtCore.QRect(10, 60, 31, 31))
        self.savedButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(61, 61, 61);\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius:15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"    image: url(:/icons/stared.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }")
        self.savedButton.setText("")
        self.savedButton.setObjectName("savedButton")
        self.menuButton = QtWidgets.QPushButton(self.centralwidget)
        self.menuButton.setGeometry(QtCore.QRect(10, 20, 31, 31))
        self.menuButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(61, 61, 61);\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius:15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"    image: url(:/icons/menu.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }")
        self.menuButton.setText("")
        self.menuButton.setObjectName("menuButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(10, 100, 31, 31))
        self.clearButton.setStyleSheet("QPushButton\n"
"{\n"
"    background-color: rgb(61, 61, 61);\n"
"    color: #fff;\n"
"    font-size: 13px;\n"
"    font-weight: bold;\n"
"    border-top-right-radius: 15px;\n"
"    border-top-left-radius:15px;\n"
"    border-bottom-right-radius: 15px;\n"
"    border-bottom-left-radius: 15px;\n"
"    padding: 10px;\n"
"\n"
"    image: url(:/icons/clear.png);\n"
"\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                       stop: 0 #dadbde, stop: 1 #f6f7fa);\n"
" }")
        self.clearButton.setText("")
        self.clearButton.setObjectName("clearButton")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(70, 60, 911, 531))
        self.background.setText("")
        self.background.setScaledContents(False)
        self.background.setObjectName("background")
        self.background.raise_()
        self.searchLineEdit.raise_()
        self.imageLabel.raise_()
        self.aboutLabel.raise_()
        self.leftButton.raise_()
        self.rightButton.raise_()
        self.searchButton.raise_()
        self.saveButton.raise_()
        self.stylelineLabel.raise_()
        self.headertextLabel.raise_()
        self.infoButton.raise_()
        self.savedButton.raise_()
        self.menuButton.raise_()
        self.clearButton.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.searchLineEdit.setPlaceholderText(_translate("MainWindow", "Введите название города"))
        self.searchButton.setText(_translate("MainWindow", "Найти"))
from ui import resources